media: media
content:
  - name: pages
    label: Pages
    path: pages
    type: collection
    filename: "{primary}.mdx"
    fields:
          - name: published
            label: Published
            type: boolean
            default: true
          - name: date
            label: Date
            type: date
          - name: title
            label: Title
            type: string
          - name: body
            label: Body
            type: rich-text