content:
  - name: pages
    label: Pages
    path: pages
    type: collection
    filename: "{primary}.mdx"
    fields:
      - name: body
        label: Body
        type: code
        options:
        language: html